### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by SleepyRiceYang** [YangQinzhu/DeepLung#2]
你好！我向询问下关于REANME中classification后Prepare Data中change `.dcm` file name, such as `1-001.dcm` to `0000001.dcm`是什么意思，如何操作呢

**Comment by YangQinzhu** [comment]
RiceYang:
&nbsp; &nbsp; &nbsp; &nbsp;您好！这个好像当时是我遇到的数据名字是不一样的，所以需要改变名字，但具体细节我记不清了。您可以先尝试运行完整的代码，看是否有报错，如果没有的话，就可以忽略这个命名问题。
感谢您使用这份代码，有问题请随时提问。时间有点远，我可能记不起具体的细节，但我会尽力答复。


祝：工作顺利。
杨





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YangQinzhu/DeepLung"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月23日(星期四) 晚上9:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[YangQinzhu/DeepLung] 代码问题 (Issue #2)





 
你好！我向询问下关于REANME中classification后Prepare Data中change .dcm file name, such as 1-001.dcm to 0000001.dcm是什么意思，如何操作呢

**Comment by SleepyRiceYang** [comment]
好的，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YangQinzhu/DeepLung"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月23日(星期四) 晚上10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YangQinzhu/DeepLung] 代码问题 (Issue #2)





 RiceYang: 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;您好！这个好像当时是我遇到的数据名字是不一样的，所以需要改变名字，但具体细节我记不清了。您可以先尝试运行完整的代码，看是否有报错，如果没有的话，就可以忽略这个命名问题。 
 感谢您使用这份代码，有问题请随时提问。时间有点远，我可能记不起具体的细节，但我会尽力答复。 
 
 
 祝：工作顺利。 
 杨 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "YangQinzhu/DeepLung"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年3月23日(星期四) 晚上9:39 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[YangQinzhu/DeepLung] 代码问题 (Issue #2) 
 
 
 
 
 
   
 你好！我向询问下关于REANME中classification后Prepare Data中change .dcm file name, such as 1-001.dcm to 0000001.dcm是什么意思，如何操作呢

**Comment by SleepyRiceYang** [comment]
你好！我第一次采用subset9作为测试集时，subset0-8作为训练集时（即run_training.sh中参数f为9），没有出现错误。但是当我更改run_training.sh参数f为8时，出现以下错误：
```Traceback (most recent call last):
  File "main.py", line 423, in <module>
    main()
  File "main.py", line 213, in main
    train(train_loader, net, loss, epoch, optimizer, get_lr, args.save_freq, save_dir) # 出现错误
  File "main.py", line 235, in train
    loss_output = loss(output, target) #！！！
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/output/detector/layers.py", line 211, in forward
    regress_losses = [0,0,0,0]
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 603, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/functional.py", line 2915, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)
RuntimeError: Found dtype Long but expected Float```
我尝试将```layes.py```中Loss函数部分中的classify_loss函数参数部分全部设置成```to.(torch.float32)```但仍然出现以上错误。
